FROM ubuntu:23.04

# Metadata
LABEL author="Jolyon Direnko-Smith"
LABEL description="An Ubuntu image providing a base for self-hosted Azure DevOps build agents."

# Set shell for RUN commands
SHELL ["/bin/bash", "--login", "-c"]

# Versions of software introduced in this image
ENV GIT_VERSION=2.39.2
ENV NVM_VERSION=0.39.3
ENV NODE_VERSION=16.20.0

# Environment variables (and aliases/synonyms) that identify Agent capabilities
ENV Git=$GIT_VERSION
ENV Node=$NODE_VERSION
ENV NodeJS=$Node
ENV Nvm=$NVM_VERSION
ENV NodeVersionManager=$Nvm


# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    git=1:$GIT_VERSION-1ubuntu1.1 \
    iputils-ping \
    libcurl4 \
    libicu72 \
    libunwind8 \
    netcat-traditional \
    libssl3 \
    libssh-4 \
  && rm -rf /var/lib/apt/lists/*


# TODO: Workaround for devops agent not supporting OpenSSL 3.0
# https://github.com/microsoft/azure-pipelines-agent/issues/3834#issuecomment-1160576447
RUN curl -sL http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb > libssl1.1_1.1.0g-2ubuntu4_amd64.deb && \
    DEBIAN_FRONTEND=noninteractive dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb && \
    rm libssl1.1_1.1.0g-2ubuntu4_amd64.deb

# https://github.com/microsoft/azure-pipelines-agent/issues/3834#issuecomment-1151874312
RUN sed -i 's/openssl_conf = openssl_init/#openssl_conf = openssl_init/g' /etc/ssl/openssl.cnf


# Install nvm (Node Version Manager)
#
# We use this to install and use specific versions of node to avoid vulnerabilities introduced
# in the version used by the build agent by default.
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v$NVM_VERSION/install.sh | bash


# Install the desired version of Node
RUN source ~/.nvm/nvm.sh \
     && nvm install $NODE_VERSION


# Install Azure Cli
RUN curl -LsS https://aka.ms/InstallAzureCLIDeb | bash \
     && rm -rf /var/lib/apt/lists/*