FROM deltics/azdevops-buildagent:wakatipu
ARG TARGETARCH=amd64

# Set shell for RUN commands
SHELL ["/bin/bash", "--login", "-c"]


# Versions of software introduced in this image
ENV AGENT_VERSION=2.190.0


# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes


# Download and run the installer for a Debian based build agent of the required version
WORKDIR /azp
RUN if [ "$TARGETARCH" = "amd64" ]; then \
      AZP_AGENTPACKAGE_URL=https://vstsagentpackage.azureedge.net/agent/${AGENT_VERSION}/vsts-agent-linux-x64-${AGENT_VERSION}.tar.gz; \
    else \
      AZP_AGENTPACKAGE_URL=https://vstsagentpackage.azureedge.net/agent/${AGENT_VERSION}/vsts-agent-linux-$TARGETARCH-${AGENT_VERSION}.tar.gz; \
    fi; \
    curl -LsS "${AZP_AGENTPACKAGE_URL}" | tar -xz

COPY ./start.sh .
RUN chmod +x start.sh

# Just to make absolutely sure that the Agent_ToolsDirectory is set correctly
#  (the folder itself is created in the wakatipu base image)
ENV Agent_ToolsDirectory=/azp/_work/_tool

ENTRYPOINT [ "./start.sh" ]