ARG BASE_IMAGE=ubuntu23.04
FROM deltics/azdevops-buildagent:$BASE_IMAGE

ARG TARGETARCH=amd64
ENV AGENT_VERSION=3.225.0

# Set shell for RUN commands
SHELL ["/bin/bash", "--login", "-c"]

# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

# Download and run the installer for a Debian based build agent of the required version
WORKDIR /azp
RUN if [ "$TARGETARCH" = "amd64" ]; then \
      AZP_AGENTPACKAGE_URL=https://vstsagentpackage.azureedge.net/agent/${AGENT_VERSION}/vsts-agent-linux-x64-${AGENT_VERSION}.tar.gz; \
    else \
      AZP_AGENTPACKAGE_URL=https://vstsagentpackage.azureedge.net/agent/${AGENT_VERSION}/vsts-agent-linux-$TARGETARCH-${AGENT_VERSION}.tar.gz; \
    fi; \
    curl -LsS "${AZP_AGENTPACKAGE_URL}" | tar -xz

COPY ./start.sh .
RUN chmod +x start.sh

RUN mkdir -p /azp/_work/_tool
ENV Agent_ToolsDirectory=/azp/_work/_tool

ENTRYPOINT [ "./start.sh" ]